//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WspolnaKasa.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WspolnaKasa.App_GlobalResources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj.
        /// </summary>
        public static string Account_ExternalLoginConfirmation_RegisterLink {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie zalogowano używając Twojego konta &lt;strong&gt;{0}&lt;/strong&gt;. Proszę podaj swój adres e-mail i kliknij przycisk {1}..
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Text {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj się.
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logowanie za pomocą zewnętrznejgo serwisu nie powiodło się..
        /// </summary>
        public static string Account_ExternalLoginFailure_Text {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logowanie nieudane.
        /// </summary>
        public static string Account_ExternalLoginFailure_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj przez.
        /// </summary>
        public static string Account_ExternalLoginsListPartial_LoginUsing {
            get {
                return ResourceManager.GetString("Account_ExternalLoginsListPartial_LoginUsing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd logowania. Upewnij się, że wprowadziłeś prawidłowe hasło..
        /// </summary>
        public static string Account_Login_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_Login_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj.
        /// </summary>
        public static string Account_Login_Login {
            get {
                return ResourceManager.GetString("Account_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj się.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj.
        /// </summary>
        public static string Account_Register_Register {
            get {
                return ResourceManager.GetString("Account_Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj się.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string AccountViewModels_Password {
            get {
                return ResourceManager.GetString("AccountViewModels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie wylogowuj mnie..
        /// </summary>
        public static string AccountViewModels_RememberMe {
            get {
                return ResourceManager.GetString("AccountViewModels_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wspólna Kasa.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj wydatek.
        /// </summary>
        public static string Dashboard_AddExpense {
            get {
                return ResourceManager.GetString("Dashboard_AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź przelew.
        /// </summary>
        public static string Dashboard_AddTransfer {
            get {
                return ResourceManager.GetString("Dashboard_AddTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kwota.
        /// </summary>
        public static string Dashboard_Amount {
            get {
                return ResourceManager.GetString("Dashboard_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kwota jest wymagana..
        /// </summary>
        public static string Dashboard_AmountRequired {
            get {
                return ResourceManager.GetString("Dashboard_AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przynajmniej jedna osoba musi zostać wybrana..
        /// </summary>
        public static string Dashboard_AtLeastOneParticipant {
            get {
                return ResourceManager.GetString("Dashboard_AtLeastOneParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można edytować wydatków innych użytkowników..
        /// </summary>
        public static string Dashboard_CannotEditOthersExpenses {
            get {
                return ResourceManager.GetString("Dashboard_CannotEditOthersExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można usuwać wydatków innych użytkowników..
        /// </summary>
        public static string Dashboard_CannotRemoveOthersExpenses {
            get {
                return ResourceManager.GetString("Dashboard_CannotRemoveOthersExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można usuwać przelewów innych użytkowników..
        /// </summary>
        public static string Dashboard_CannotRemoveOthersTransfers {
            get {
                return ResourceManager.GetString("Dashboard_CannotRemoveOthersTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwórz.
        /// </summary>
        public static string Dashboard_CreateButton {
            get {
                return ResourceManager.GetString("Dashboard_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stwórz nową lub dołącz do istniejącej grupy.
        /// </summary>
        public static string Dashboard_CreateJoinGroup {
            get {
                return ResourceManager.GetString("Dashboard_CreateJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data.
        /// </summary>
        public static string Dashboard_Date {
            get {
                return ResourceManager.GetString("Dashboard_Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data jest wymagana..
        /// </summary>
        public static string Dashboard_DateRequired {
            get {
                return ResourceManager.GetString("Dashboard_DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        public static string Dashboard_Description {
            get {
                return ResourceManager.GetString("Dashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis jest wymagany..
        /// </summary>
        public static string Dashboard_DescriptionRequired {
            get {
                return ResourceManager.GetString("Dashboard_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj wydatek.
        /// </summary>
        public static string Dashboard_EditExpense {
            get {
                return ResourceManager.GetString("Dashboard_EditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj grupę.
        /// </summary>
        public static string Dashboard_EditGroup {
            get {
                return ResourceManager.GetString("Dashboard_EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupa.
        /// </summary>
        public static string Dashboard_Group {
            get {
                return ResourceManager.GetString("Dashboard_Group", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Groupa o podanej nazwie już istnieje..
        /// </summary>
        public static string Dashboard_GroupAlreadyExists {
            get {
                return ResourceManager.GetString("Dashboard_GroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Groupa o podanej nazwie nie istnieje..
        /// </summary>
        public static string Dashboard_GroupDoesNotExist {
            get {
                return ResourceManager.GetString("Dashboard_GroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa grupy.
        /// </summary>
        public static string Dashboard_GroupName {
            get {
                return ResourceManager.GetString("Dashboard_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa grupy jest wymagana..
        /// </summary>
        public static string Dashboard_GroupNameRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybór grupy jest wymagany..
        /// </summary>
        public static string Dashboard_GroupRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło grupy.
        /// </summary>
        public static string Dashboard_GroupSecret {
            get {
                return ResourceManager.GetString("Dashboard_GroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło grupy jest wymagane..
        /// </summary>
        public static string Dashboard_GroupSecretRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupSecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz grupę....
        /// </summary>
        public static string Dashboard_GroupSelect {
            get {
                return ResourceManager.GetString("Dashboard_GroupSelect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawne hasło grupy..
        /// </summary>
        public static string Dashboard_IncorrectGroupSecret {
            get {
                return ResourceManager.GetString("Dashboard_IncorrectGroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wydatki.
        /// </summary>
        public static string Dashboard_Index_Expenses {
            get {
                return ResourceManager.GetString("Dashboard_Index_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualności.
        /// </summary>
        public static string Dashboard_Index_News {
            get {
                return ResourceManager.GetString("Dashboard_Index_News", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kokpit.
        /// </summary>
        public static string Dashboard_Index_Title {
            get {
                return ResourceManager.GetString("Dashboard_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przelewy.
        /// </summary>
        public static string Dashboard_Index_Transfers {
            get {
                return ResourceManager.GetString("Dashboard_Index_Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dołącz.
        /// </summary>
        public static string Dashboard_JoinButton {
            get {
                return ResourceManager.GetString("Dashboard_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Członkowie grupy.
        /// </summary>
        public static string Dashboard_ModalAddExpense_GroupMembers {
            get {
                return ResourceManager.GetString("Dashboard_ModalAddExpense_GroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowa nazwa.
        /// </summary>
        public static string Dashboard_NewGroupName {
            get {
                return ResourceManager.GetString("Dashboard_NewGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ludzie.
        /// </summary>
        public static string Dashboard_People {
            get {
                return ResourceManager.GetString("Dashboard_People", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Osoba.
        /// </summary>
        public static string Dashboard_Person {
            get {
                return ResourceManager.GetString("Dashboard_Person", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Od kogo.
        /// </summary>
        public static string Dashboard_PersonFrom {
            get {
                return ResourceManager.GetString("Dashboard_PersonFrom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do kogo.
        /// </summary>
        public static string Dashboard_PersonTo {
            get {
                return ResourceManager.GetString("Dashboard_PersonTo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kwota musi być dodatnia..
        /// </summary>
        public static string Dashboard_PositiveAmount {
            get {
                return ResourceManager.GetString("Dashboard_PositiveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń.
        /// </summary>
        public static string Dashboard_Remove {
            get {
                return ResourceManager.GetString("Dashboard_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń wydatek.
        /// </summary>
        public static string Dashboard_RemoveExpense {
            get {
                return ResourceManager.GetString("Dashboard_RemoveExpense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć transakcję?.
        /// </summary>
        public static string Dashboard_RemoveExpenseConfirmationText {
            get {
                return ResourceManager.GetString("Dashboard_RemoveExpenseConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń grupę.
        /// </summary>
        public static string Dashboard_RemoveGroup {
            get {
                return ResourceManager.GetString("Dashboard_RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć grupę? Usuniętę zostaną wszystkie wydatki i przelewy..
        /// </summary>
        public static string Dashboard_RemoveGroupConfirmationText {
            get {
                return ResourceManager.GetString("Dashboard_RemoveGroupConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń przelew.
        /// </summary>
        public static string Dashboard_RemoveTransfer {
            get {
                return ResourceManager.GetString("Dashboard_RemoveTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć przelew?.
        /// </summary>
        public static string Dashboard_RemoveTransferConfirmationText {
            get {
                return ResourceManager.GetString("Dashboard_RemoveTransferConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz zmiany.
        /// </summary>
        public static string Dashboard_SaveChanges {
            get {
                return ResourceManager.GetString("Dashboard_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Razem.
        /// </summary>
        public static string Dashboard_Summary_Total {
            get {
                return ResourceManager.GetString("Dashboard_Summary_Total", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tytuł.
        /// </summary>
        public static string Dashboard_TransferTitle {
            get {
                return ResourceManager.GetString("Dashboard_TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystko rozliczone!.
        /// </summary>
        public static string GroupsSidebar_AllSettled {
            get {
                return ResourceManager.GetString("GroupsSidebar_AllSettled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przejdź do kokpitu.
        /// </summary>
        public static string Home_Index_GetStarted {
            get {
                return ResourceManager.GetString("Home_Index_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prowadź historię wydatków.
        /// </summary>
        public static string Home_Index_History {
            get {
                return ResourceManager.GetString("Home_Index_History", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie wiesz na co uciekła kasa? Po prostu zerknij w historię swojej grupy..
        /// </summary>
        public static string Home_Index_HistoryText {
            get {
                return ResourceManager.GetString("Home_Index_HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapraszaj znajomych.
        /// </summary>
        public static string Home_Index_InviteFriends {
            get {
                return ResourceManager.GetString("Home_Index_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ciężko rozliczać wspólne wydatki samemu. Zaproś znajomych!.
        /// </summary>
        public static string Home_Index_InviteFriendsText {
            get {
                return ResourceManager.GetString("Home_Index_InviteFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozliczaj wspólne wydatki ze znajomymi. Szybko i łatwo. Bez żadnych nieporozumień..
        /// </summary>
        public static string Home_Index_Lead {
            get {
                return ResourceManager.GetString("Home_Index_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozliczaj.
        /// </summary>
        public static string Home_Index_Split {
            get {
                return ResourceManager.GetString("Home_Index_Split", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisuj na bieżąco wspólne wydatki i bądź na bieżąco. Bez zaskoczeń, kto ile komu wisi..
        /// </summary>
        public static string Home_Index_SplitText {
            get {
                return ResourceManager.GetString("Home_Index_SplitText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień.
        /// </summary>
        public static string Manage_ChangePassword_Button {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        public static string Manage_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień.
        /// </summary>
        public static string Manage_Index_Change {
            get {
                return ResourceManager.GetString("Manage_Index_Change", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        public static string Manage_Index_ChangePassword {
            get {
                return ResourceManager.GetString("Manage_Index_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię i nazwisko.
        /// </summary>
        public static string Manage_Index_DisplayName {
            get {
                return ResourceManager.GetString("Manage_Index_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiązane konta.
        /// </summary>
        public static string Manage_Index_ExternalLogin {
            get {
                return ResourceManager.GetString("Manage_Index_ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarządzaj.
        /// </summary>
        public static string Manage_Index_ManageExternalLogins {
            get {
                return ResourceManager.GetString("Manage_Index_ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Haslo zostało zmienione..
        /// </summary>
        public static string Manage_Index_MessageChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Index_MessageChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd..
        /// </summary>
        public static string Manage_Index_MessageError {
            get {
                return ResourceManager.GetString("Manage_Index_MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło zostało ustawione..
        /// </summary>
        public static string Manage_Index_MessageSetPasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Index_MessageSetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        public static string Manage_Index_Password {
            get {
                return ResourceManager.GetString("Manage_Index_Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustaw hasło.
        /// </summary>
        public static string Manage_Index_SetPassword {
            get {
                return ResourceManager.GetString("Manage_Index_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia profilu.
        /// </summary>
        public static string Manage_Index_Title {
            get {
                return ResourceManager.GetString("Manage_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Połącz.
        /// </summary>
        public static string Manage_ManageLogins_Connect {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozłącz.
        /// </summary>
        public static string Manage_ManageLogins_RemoveLink {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiązane konta.
        /// </summary>
        public static string Manage_ManageLogins_Title {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustaw hasło, żeby nie musieć korzystać z logowania przez Facebooka..
        /// </summary>
        public static string Manage_SetPassword_Text {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustaw hasło.
        /// </summary>
        public static string Manage_SetPassword_Title {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bieżące hasło.
        /// </summary>
        public static string ManageViewModels_CurrentPassword {
            get {
                return ResourceManager.GetString("ManageViewModels_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowe hasło.
        /// </summary>
        public static string ManageViewModels_NewPassword {
            get {
                return ResourceManager.GetString("ManageViewModels_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustaw.
        /// </summary>
        public static string SetPassword_Button {
            get {
                return ResourceManager.GetString("SetPassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podczas przetwarzania żądania wystąpił błąd. Proszę spróbować ponownie poźniej..
        /// </summary>
        public static string Shared_Error_Text {
            get {
                return ResourceManager.GetString("Shared_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystapił błąd.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konto zostało zablokowane, proszę spróbować później..
        /// </summary>
        public static string Shared_Lockout_Text {
            get {
                return ResourceManager.GetString("Shared_Lockout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Konto zablokowane.
        /// </summary>
        public static string Shared_Lockout_Title {
            get {
                return ResourceManager.GetString("Shared_Lockout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyloguj.
        /// </summary>
        public static string Shared_LoginPartial_LogOffButton {
            get {
                return ResourceManager.GetString("Shared_LoginPartial_LogOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E-mail.
        /// </summary>
        public static string ViewModels_Email {
            get {
                return ResourceManager.GetString("ViewModels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E-mail jest wymagany..
        /// </summary>
        public static string ViewModels_EmailRequired {
            get {
                return ResourceManager.GetString("ViewModels_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podany adres e-mail jest niepoprawny..
        /// </summary>
        public static string ViewModels_InvalidEmail {
            get {
                return ResourceManager.GetString("ViewModels_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdź hasło.
        /// </summary>
        public static string ViewModels_PasswordConfirm {
            get {
                return ResourceManager.GetString("ViewModels_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło musi mieć co najmniej 6 znaków..
        /// </summary>
        public static string ViewModels_PasswordMinimumLength {
            get {
                return ResourceManager.GetString("ViewModels_PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło jest wymagane..
        /// </summary>
        public static string ViewModels_PasswordRequired {
            get {
                return ResourceManager.GetString("ViewModels_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podane hasła nie zgadzają się..
        /// </summary>
        public static string ViewModels_PasswordsNotMatching {
            get {
                return ResourceManager.GetString("ViewModels_PasswordsNotMatching", resourceCulture);
            }
        }
    }
}
