//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WspolnaKasa.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WspolnaKasa.App_GlobalResources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zalogować.
        /// </summary>
        public static string Account_ConfirmEmail_LinkText {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za potwierdzenie adresu e-mail. Teraz możesz się.
        /// </summary>
        public static string Account_ConfirmEmail_Text {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail został potwierdzony.
        /// </summary>
        public static string Account_ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Account_ExternalLoginConfirmation_RegisterLink {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie zalogowano używając Twojego konta &lt;strong&gt;{0}&lt;/strong&gt;. Proszę podaj swój adres e-mail i kliknij przycisk {1}..
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Text {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie za pomocą zewnętrznejgo serwisu nie powiodło się..
        /// </summary>
        public static string Account_ExternalLoginFailure_Text {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieudane.
        /// </summary>
        public static string Account_ExternalLoginFailure_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj przez.
        /// </summary>
        public static string Account_ExternalLoginsListPartial_LoginUsing {
            get {
                return ResourceManager.GetString("Account_ExternalLoginsListPartial_LoginUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontynuuj.
        /// </summary>
        public static string Account_ForgotPassword_Continue {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź adres e-mail..
        /// </summary>
        public static string Account_ForgotPassword_Email {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string Account_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na podany adres e-mail została wysłana wiadomość. Jeśli wiadomość nie przyszła w ciągu kilku minut, spróbuj pomownie. Sprawdź także folder spam..
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Text {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string Account_Login_ForgotPasswordLink {
            get {
                return ResourceManager.GetString("Account_Login_ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania. Upewnij się, że wprowadziłeś prawidłowe hasło..
        /// </summary>
        public static string Account_Login_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_Login_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Account_Login_Login {
            get {
                return ResourceManager.GetString("Account_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Account_Register_Register {
            get {
                return ResourceManager.GetString("Account_Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw nowe hasło.
        /// </summary>
        public static string Account_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zalogować.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_LinkText {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało zmienione. Teraz możesz się.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Text {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zostało zmienione.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string AccountViewModels_Password {
            get {
                return ResourceManager.GetString("AccountViewModels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wylogowuj mnie..
        /// </summary>
        public static string AccountViewModels_RememberMe {
            get {
                return ResourceManager.GetString("AccountViewModels_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy,&lt;br/&gt;&lt;br /&gt;Proszę &lt;a href=&quot;{0}&quot;&gt;kliknij tutaj&lt;/a&gt;, by potwierdzić swój adres e-mail w serwisie &lt;a href=&quot;https://wspolnakasa.azurewebsites.net&quot;&gt;Wspólna Kasa&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;Jeśli to nie Ty dokonałeś rejestracji, zignoruj tę wiadomość.&lt;br/&gt;&lt;br /&gt;Pozdrawiamy!.
        /// </summary>
        public static string ActivationMail_Body {
            get {
                return ResourceManager.GetString("ActivationMail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź swój profil.
        /// </summary>
        public static string ActivationMail_Subject {
            get {
                return ResourceManager.GetString("ActivationMail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wspólna Kasa.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razem.
        /// </summary>
        public static string Dasgboard_Summary_Total {
            get {
                return ResourceManager.GetString("Dasgboard_Summary_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydatek.
        /// </summary>
        public static string Dashboard_AddExpense {
            get {
                return ResourceManager.GetString("Dashboard_AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź przelew.
        /// </summary>
        public static string Dashboard_AddTransfer {
            get {
                return ResourceManager.GetString("Dashboard_AddTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string Dashboard_Amount {
            get {
                return ResourceManager.GetString("Dashboard_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota jest wymagana..
        /// </summary>
        public static string Dashboard_AmountRequired {
            get {
                return ResourceManager.GetString("Dashboard_AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jedna osoba musi zostać wybrana..
        /// </summary>
        public static string Dashboard_AtLeastOneParticipant {
            get {
                return ResourceManager.GetString("Dashboard_AtLeastOneParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można edytować wydatków innych użytkowników..
        /// </summary>
        public static string Dashboard_CannotEditOthersExpenses {
            get {
                return ResourceManager.GetString("Dashboard_CannotEditOthersExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usuwać wydatków innych użytkowników..
        /// </summary>
        public static string Dashboard_CannotRemoveOthersExpenses {
            get {
                return ResourceManager.GetString("Dashboard_CannotRemoveOthersExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        public static string Dashboard_CreateButton {
            get {
                return ResourceManager.GetString("Dashboard_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz nową lub dołącz do istniejącej grupy.
        /// </summary>
        public static string Dashboard_CreateJoinGroup {
            get {
                return ResourceManager.GetString("Dashboard_CreateJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Dashboard_Date {
            get {
                return ResourceManager.GetString("Dashboard_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data jest wymagana..
        /// </summary>
        public static string Dashboard_DateRequired {
            get {
                return ResourceManager.GetString("Dashboard_DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Dashboard_Description {
            get {
                return ResourceManager.GetString("Dashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest wymagany..
        /// </summary>
        public static string Dashboard_DescriptionRequired {
            get {
                return ResourceManager.GetString("Dashboard_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj wydatek.
        /// </summary>
        public static string Dashboard_EditExpense {
            get {
                return ResourceManager.GetString("Dashboard_EditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj grupę.
        /// </summary>
        public static string Dashboard_EditGroup {
            get {
                return ResourceManager.GetString("Dashboard_EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        public static string Dashboard_Group {
            get {
                return ResourceManager.GetString("Dashboard_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupa o podanej nazwie już istnieje..
        /// </summary>
        public static string Dashboard_GroupAlreadyExists {
            get {
                return ResourceManager.GetString("Dashboard_GroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupa o podanej nazwie nie istnieje..
        /// </summary>
        public static string Dashboard_GroupDoesNotExist {
            get {
                return ResourceManager.GetString("Dashboard_GroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa grupy.
        /// </summary>
        public static string Dashboard_GroupName {
            get {
                return ResourceManager.GetString("Dashboard_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa grupy jest wymagana..
        /// </summary>
        public static string Dashboard_GroupNameRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór grupy jest wymagany..
        /// </summary>
        public static string Dashboard_GroupRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło grupy.
        /// </summary>
        public static string Dashboard_GroupSecret {
            get {
                return ResourceManager.GetString("Dashboard_GroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło grupy jest wymagane..
        /// </summary>
        public static string Dashboard_GroupSecretRequired {
            get {
                return ResourceManager.GetString("Dashboard_GroupSecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz grupę....
        /// </summary>
        public static string Dashboard_GroupSelect {
            get {
                return ResourceManager.GetString("Dashboard_GroupSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne hasło grupy..
        /// </summary>
        public static string Dashboard_IncorrectGroupSecret {
            get {
                return ResourceManager.GetString("Dashboard_IncorrectGroupSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki.
        /// </summary>
        public static string Dashboard_Index_Expenses {
            get {
                return ResourceManager.GetString("Dashboard_Index_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualności.
        /// </summary>
        public static string Dashboard_Index_News {
            get {
                return ResourceManager.GetString("Dashboard_Index_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kokpit.
        /// </summary>
        public static string Dashboard_Index_Title {
            get {
                return ResourceManager.GetString("Dashboard_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelewy.
        /// </summary>
        public static string Dashboard_Index_Transfers {
            get {
                return ResourceManager.GetString("Dashboard_Index_Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dołącz.
        /// </summary>
        public static string Dashboard_JoinButton {
            get {
                return ResourceManager.GetString("Dashboard_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członkowie grupy.
        /// </summary>
        public static string Dashboard_ModalAddExpense_GroupMembers {
            get {
                return ResourceManager.GetString("Dashboard_ModalAddExpense_GroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa nazwa.
        /// </summary>
        public static string Dashboard_NewGroupName {
            get {
                return ResourceManager.GetString("Dashboard_NewGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ludzie.
        /// </summary>
        public static string Dashboard_People {
            get {
                return ResourceManager.GetString("Dashboard_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba.
        /// </summary>
        public static string Dashboard_Person {
            get {
                return ResourceManager.GetString("Dashboard_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od kogo.
        /// </summary>
        public static string Dashboard_PersonFrom {
            get {
                return ResourceManager.GetString("Dashboard_PersonFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do kogo.
        /// </summary>
        public static string Dashboard_PersonTo {
            get {
                return ResourceManager.GetString("Dashboard_PersonTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota musi być dodatnia..
        /// </summary>
        public static string Dashboard_PositiveAmount {
            get {
                return ResourceManager.GetString("Dashboard_PositiveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Dashboard_Remove {
            get {
                return ResourceManager.GetString("Dashboard_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wydatek.
        /// </summary>
        public static string Dashboard_RemoveExpense {
            get {
                return ResourceManager.GetString("Dashboard_RemoveExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć transakcję?.
        /// </summary>
        public static string Dashboard_RemoveExpenseConfirmationText {
            get {
                return ResourceManager.GetString("Dashboard_RemoveExpenseConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń grupę.
        /// </summary>
        public static string Dashboard_RemoveGroup {
            get {
                return ResourceManager.GetString("Dashboard_RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć grupę? Usuniętę zostaną wszystkie wydatki i przelewy..
        /// </summary>
        public static string Dashboard_RemoveGroupConfirmationText {
            get {
                return ResourceManager.GetString("Dashboard_RemoveGroupConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        public static string Dashboard_SaveChanges {
            get {
                return ResourceManager.GetString("Dashboard_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Dashboard_TransferTitle {
            get {
                return ResourceManager.GetString("Dashboard_TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy,&lt;br /&gt;&lt;br /&gt;Proszę &lt;a href=&quot;{0}&quot;&gt;kliknij tutaj&lt;/a&gt;, by zmienić swoje hasło w serwisie &lt;a href=&quot;https://wspolnakasa.azurewebsites.net&quot;&gt;Wspólna Kasa&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;Jeśli to nie Ty poprosiłeś o zmianę hasła, zignoruj tę wiadomość.&lt;br /&gt;&lt;br /&gt;Pozdrawiamy!.
        /// </summary>
        public static string ForgotPasswordEmail_Body {
            get {
                return ResourceManager.GetString("ForgotPasswordEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string ForgotPasswordEmail_Subject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź do kokpitu.
        /// </summary>
        public static string Home_Index_GetStarted {
            get {
                return ResourceManager.GetString("Home_Index_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prowadź historię wydatków.
        /// </summary>
        public static string Home_Index_History {
            get {
                return ResourceManager.GetString("Home_Index_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wiesz na co uciekła kasa? Po prostu zerknij w historię swojej grupy..
        /// </summary>
        public static string Home_Index_HistoryText {
            get {
                return ResourceManager.GetString("Home_Index_HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapraszaj znajomych.
        /// </summary>
        public static string Home_Index_InviteFriends {
            get {
                return ResourceManager.GetString("Home_Index_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciężko rozliczać wspólne wydatki samemu. Zaproś znajomych!.
        /// </summary>
        public static string Home_Index_InviteFriendsText {
            get {
                return ResourceManager.GetString("Home_Index_InviteFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozliczaj wspólne wydatki ze znajomymi. Szybko i łatwo. Bez żadnych nieporozumień..
        /// </summary>
        public static string Home_Index_Lead {
            get {
                return ResourceManager.GetString("Home_Index_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozliczaj.
        /// </summary>
        public static string Home_Index_Split {
            get {
                return ResourceManager.GetString("Home_Index_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisuj na bieżąco wspólne wydatki i bądź na bieżąco. Bez zaskoczeń, kto ile komu wisi..
        /// </summary>
        public static string Home_Index_SplitText {
            get {
                return ResourceManager.GetString("Home_Index_SplitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string Manage_ChangePassword_Button {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string Manage_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string Manage_Index_Change {
            get {
                return ResourceManager.GetString("Manage_Index_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string Manage_Index_ChangePassword {
            get {
                return ResourceManager.GetString("Manage_Index_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string Manage_Index_DisplayName {
            get {
                return ResourceManager.GetString("Manage_Index_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiązane konta.
        /// </summary>
        public static string Manage_Index_ExternalLogin {
            get {
                return ResourceManager.GetString("Manage_Index_ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj.
        /// </summary>
        public static string Manage_Index_ManageExternalLogins {
            get {
                return ResourceManager.GetString("Manage_Index_ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haslo zostało zmienione..
        /// </summary>
        public static string Manage_Index_MessageChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Index_MessageChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd..
        /// </summary>
        public static string Manage_Index_MessageError {
            get {
                return ResourceManager.GetString("Manage_Index_MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zostało ustawione..
        /// </summary>
        public static string Manage_Index_MessageSetPasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Index_MessageSetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Manage_Index_Password {
            get {
                return ResourceManager.GetString("Manage_Index_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło.
        /// </summary>
        public static string Manage_Index_SetPassword {
            get {
                return ResourceManager.GetString("Manage_Index_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia profilu.
        /// </summary>
        public static string Manage_Index_Title {
            get {
                return ResourceManager.GetString("Manage_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz.
        /// </summary>
        public static string Manage_ManageLogins_Connect {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozłącz.
        /// </summary>
        public static string Manage_ManageLogins_RemoveLink {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiązane konta.
        /// </summary>
        public static string Manage_ManageLogins_Title {
            get {
                return ResourceManager.GetString("Manage_ManageLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło, żeby nie musieć korzystać z logowania przez Facebooka..
        /// </summary>
        public static string Manage_SetPassword_Text {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło.
        /// </summary>
        public static string Manage_SetPassword_Title {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bieżące hasło.
        /// </summary>
        public static string ManageViewModels_CurrentPassword {
            get {
                return ResourceManager.GetString("ManageViewModels_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string ManageViewModels_NewPassword {
            get {
                return ResourceManager.GetString("ManageViewModels_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw.
        /// </summary>
        public static string SetPassword_Button {
            get {
                return ResourceManager.GetString("SetPassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas przetwarzania żądania wystąpił błąd. Proszę spróbować ponownie lub wysłać e-mail z opisem problemu na &lt;a href=&quot;mailto:kontakt@wspolnakasa.pl&quot;&gt;kontakt@wspolnakasa.pl&lt;/a&gt;..
        /// </summary>
        public static string Shared_Error_Text {
            get {
                return ResourceManager.GetString("Shared_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystapił błąd.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto zostało zablokowane, proszę spróbować później..
        /// </summary>
        public static string Shared_Lockout_Text {
            get {
                return ResourceManager.GetString("Shared_Lockout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto zablokowane.
        /// </summary>
        public static string Shared_Lockout_Title {
            get {
                return ResourceManager.GetString("Shared_Lockout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Shared_LoginPartial_LogOffButton {
            get {
                return ResourceManager.GetString("Shared_LoginPartial_LogOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string ViewModels_Email {
            get {
                return ResourceManager.GetString("ViewModels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail jest wymagany..
        /// </summary>
        public static string ViewModels_EmailRequired {
            get {
                return ResourceManager.GetString("ViewModels_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres e-mail jest niepoprawny..
        /// </summary>
        public static string ViewModels_InvalidEmail {
            get {
                return ResourceManager.GetString("ViewModels_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string ViewModels_PasswordConfirm {
            get {
                return ResourceManager.GetString("ViewModels_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć co najmniej 6 znaków..
        /// </summary>
        public static string ViewModels_PasswordMinimumLength {
            get {
                return ResourceManager.GetString("ViewModels_PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest wymagane..
        /// </summary>
        public static string ViewModels_PasswordRequired {
            get {
                return ResourceManager.GetString("ViewModels_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podane hasła nie zgadzają się..
        /// </summary>
        public static string ViewModels_PasswordsNotMatching {
            get {
                return ResourceManager.GetString("ViewModels_PasswordsNotMatching", resourceCulture);
            }
        }
    }
}
